diff --git a/Makefile b/Makefile
index f4be9d1..b29b09c 100644
--- a/Makefile
+++ b/Makefile
@@ -5,6 +5,7 @@ include config.mk
 
 SRC = drw.c dmenu.c stest.c util.c
 OBJ = $(SRC:.c=.o)
+PREFIX = $(HOME)/.local
 
 all: options dmenu stest
 
