--[[ KOLORS ]]--
vim.highlight.create("Comment", { ctermfg = "244" })
vim.highlight.create("Constant", { ctermfg = "cyan" })
vim.highlight.create("String", { ctermfg = "green" })
vim.highlight.create("Character", { ctermfg = "green" })
vim.highlight.create("Number", { ctermfg = "yellow" })
vim.highlight.create("Boolean", { ctermfg = "yellow" })
vim.highlight.create("Float", { ctermfg = "yellow" })
vim.highlight.create("Identifier", { ctermfg = "red" })
vim.highlight.create("Function", { ctermfg = "blue" })
vim.highlight.create("Statement", { ctermfg = "magenta" })
vim.highlight.create("Conditional", { ctermfg = "magenta" })
vim.highlight.create("Repeat", { ctermfg = "magenta" })
vim.highlight.create("Label", { ctermfg = "magenta" })
vim.highlight.create("Operator", { ctermfg = "magenta" })
vim.highlight.create("Keyword", { ctermfg = "red" })
vim.highlight.create("Exception", { ctermfg = "magenta" })
vim.highlight.create("PreProc", { ctermfg = "yellow" })
vim.highlight.create("Include", { ctermfg = "blue" })
vim.highlight.create("Define", { ctermfg = "magenta" })
vim.highlight.create("Macro", { ctermfg = "magenta" })
vim.highlight.create("PreCondit", { ctermfg = "yellow" })
vim.highlight.create("Type", { ctermfg = "yellow" })
vim.highlight.create("StorageClass", { ctermfg = "yellow" })
vim.highlight.create("Structure", { ctermfg = "yellow" })
vim.highlight.create("Typedef", { ctermfg = "yellow" })
vim.highlight.create("Special", { ctermfg = "blue" })
vim.highlight.create("SpecialChar", { ctermfg = "yellow" })
vim.highlight.create("SpecialComment", { ctermfg = "gray" })
vim.highlight.create("Error", { ctermfg = "red" })
vim.highlight.create("Todo", { ctermfg = "magenta" })

vim.highlight.create("CursorLine", { cterm = "NONE" })
vim.highlight.create("Directory", { ctermfg = "white" })
vim.highlight.create("EndOfBuffer", { ctermfg = "237" })
vim.highlight.create("ErrorMsg", { ctermbg = "NONE", ctermfg = "red" })
vim.highlight.create("VertSplit", { ctermbg = "237", ctermfg = "237" })
vim.highlight.create("Substitute", { ctermbg = "yellow", ctermfg = "black" })
vim.highlight.create("LineNr", { ctermfg = "239" })
vim.highlight.create("CursorLineNr", { cterm = "NONE", ctermfg = "gray" })
vim.highlight.create("MatchParen", { ctermbg = "magenta", ctermfg = "black" })
vim.highlight.create("NonText", { ctermfg = "237" })
vim.highlight.create("Pmenu", { ctermbg = "darkgray", ctermfg = "white" })
vim.highlight.create("PmenuSel", { ctermbg = "blue", ctermfg = "black" })
vim.highlight.create("PmenuSbar", { ctermbg = "NONE" })
vim.highlight.create("PmenuThumb", { ctermbg = "NONE" })
vim.highlight.create("Question", { ctermbg = "NONE", ctermfg = "magenta" })
vim.highlight.create("QuickFixLine", { ctermbg = "yellow", ctermfg = "black" })
vim.highlight.create("Search", { ctermbg = "yellow", ctermfg = "black" })
vim.highlight.create("StatusLine", { ctermbg = "gray", ctermfg = "237" })
vim.highlight.create("StatusLineExtra", { ctermbg = "white", ctermfg = "black" })
vim.highlight.create("StatuslineAccent", { ctermbg = "blue", ctermfg = "black" })
vim.highlight.create("StatuslineInsertAccent", { ctermbg = "green", ctermfg = "black" })
vim.highlight.create("StatuslineVisualAccent", { ctermbg = "magenta", ctermfg = "black" })
vim.highlight.create("StatuslineSelect", { ctermbg = "red", ctermfg = "black" })
vim.highlight.create("StatuslineReplaceaccent", { ctermbg = "red", ctermfg = "black" })
vim.highlight.create("StatuslineCmdLineAccent", { ctermbg = "yellow", ctermfg = "black" })
vim.highlight.create("StatuslineTerminalAccent", { ctermbg = "cyan", ctermfg = "black" })
vim.highlight.create("StatusLineNC", { ctermbg = "237", ctermfg = "237" })
vim.highlight.create("TabLine", { cterm = "NONE", ctermbg = "NONE", ctermfg = "240" })
vim.highlight.create("TabLineFill", { ctermbg = "black", ctermfg = "black" })
vim.highlight.create("TabLineSel", { ctermbg = "237", ctermfg = "gray" })
vim.highlight.create("Title", { ctermfg = "green" })
vim.highlight.create("Visual", { ctermbg = "239" })
vim.highlight.create("WarningMsg", { ctermbg = "NONE", ctermfg = "red" })
vim.highlight.create("WildMenu", { ctermbg = "blue", ctermfg = "black" })

vim.highlight.create("netrwDir", { ctermbg = "NONE", ctermfg = "252" })
vim.highlight.create("netrwPlain", { ctermbg = "NONE", ctermfg = "blue" })
vim.highlight.create("netrwSlash", { ctermbg = "NONE", ctermfg = "magenta" })
