#!/bin/sh

waybar &

riverctl map normal Super Space spawn "bemenu-run -H 34 --ch 24 --fn 'JetBrainsMono Nerd Font [10]' -p 'debian  ' --tb '#2d2d2d' --tf '#f2777a' --fb '#2d2d2d' --ff '#6699cc' --nb '#2d2d2d' --nf '#747369' --hb '#2d2d2d' --hf '#d3d0c8' --ab '#2d2d2d' --af '#747369'"

riverctl map normal Super Return spawn st
riverctl map normal Super+Control Return spawn "say tmux; st -e tmux attach -t TMUX"
riverctl map normal Super+Shift Period spawn "jpg2ff < $(find /home/triplek/MEGA/wallhaven -type f -printf "%T+\t%p\n" | sort -r | awk '{print $2}' | shuf -n 1) > ~/.cache/st_bg.ff; say refstbg; pidof st | xargs kill -s USR1"
riverctl map normal Super+Shift Comma spawn "jpg2ff < $(find /home/triplek/MEGA/WallHaven -type f -printf "%T+\t%p\n" | sort -r | awk '{print $2}' | shuf -n 1) > ~/.cache/st_bg.ff; say refstbg; pidof st | xargs kill -s USR1"

riverctl map normal Super+Shift B spawn qutebrowser

riverctl map normal Super W close

riverctl map normal Super+Shift Q exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super+Shift Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

riverctl focus-follows-cursor normal
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Tab focus-previous-tags

riverctl map normal Super S toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy'

for mode in normal locked
do
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl s +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl s 5%-'
    
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

done

riverctl background-color 0x2d2d2d
riverctl border-color-focused 0xd3d0c8
riverctl border-color-unfocused 0x747369

riverctl set-repeat 50 300

riverctl default-layout rivertile
exec rivertile -view-padding 4 -outer-padding 4
