diff --git a/Makefile b/Makefile
index cbdc985..e028818 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ version = 26
 srcdir = .
 VPATH = $(srcdir)
 
-PREFIX = /usr/local
+PREFIX = $(HOME)/.local
 MANPREFIX = $(PREFIX)/share/man
 
 # autoreload backend: inotify/nop
